CREATE TABLE uwm.powiat 
(id serial,
 kod_teryt varchar(20), 
 fk_woj bigint , 
 nazwa varchar(100),
  PRIMARY KEY (id)
);
CREATE INDEX ix_powiat_nazwa ON uwm.powiat (nazwa);
CREATE INDEX ix_powiat_fk_woj ON uwm.powiat (fk_woj);

INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2817', '28', '2817', 'SZCZYCIEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('416', '4', '0416', 'TUCHOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2807', '28', '2807', 'IŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3211', '32', '3211', 'POLICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2203', '22', '2203', 'CZŁUCHOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2004', '20', '2004', 'GRAJEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2202', '22', '2202', 'CHOJNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2207', '22', '2207', 'KWidZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2814', '28', '2814', 'OLSZTYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2862', '28', '2862', 'M. OLSZTYN');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3216', '32', '3216', 'ŚWidWIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2805', '28', '2805', 'EŁCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2810', '28', '2810', 'MRĄGOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2001', '20', '2001', 'AUGUSTOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3205', '32', '3205', 'GRYFICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2213', '22', '2213', 'STAROGARDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3263', '32', '3263', 'M. ŚWINOUJŚCIE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2209', '22', '2209', 'MALBORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3207', '32', '3207', 'KAMIEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2806', '28', '2806', 'GIŻYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2813', '28', '2813', 'OLECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2214', '22', '2214', 'TCZEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2808', '28', '2808', 'KĘTRZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2206', '22', '2206', 'KOŚCIERSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2809', '28', '2809', 'LidZBARSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('219', '2', '0219', 'ŚWidNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1601', '16', '1601', 'BRZESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2604', '26', '2604', 'KIELECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2661', '26', '2661', 'M. KIELCE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('604', '6', '0604', 'HRUBIESZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2406', '24', '2406', 'KŁOBUCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('215', '2', '0215', 'OŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('206', '2', '0206', 'JELENIOGÓRSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('261', '2', '0261', 'M. JELENIA GÓRA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2607', '26', '2607', 'OSTROWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1604', '16', '1604', 'KLUCZBORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2611', '26', '2611', 'STARACHOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('606', '6', '0606', 'KRASNOSTAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1012', '10', '1012', 'RADOMSZCZAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1606', '16', '1606', 'NAMYSŁOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('205', '2', '0205', 'JAWORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2610', '26', '2610', 'SKARŻYSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('223', '2', '0223', 'WROCŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1009', '10', '1009', 'PAJĘCZAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('212', '2', '0212', 'LWÓWECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('226', '2', '0226', 'ZŁOTORYJSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('612', '6', '0612', 'OPOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1409', '14', '1409', 'LIPSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('214', '2', '0214', 'OLEŚNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1017', '10', '1017', 'WIELUŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2605', '26', '2605', 'KONECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('209', '2', '0209', 'LEGNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('262', '2', '0262', 'M. LEGNICA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1430', '14', '1430', 'SZYDŁOWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3008', '30', '3008', 'KĘPIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1018', '10', '1018', 'WIERUSZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('609', '6', '0609', 'LUBELSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('201', '2', '0201', 'BOLESŁAWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('220', '2', '0220', 'TRZEBNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('222', '2', '0222', 'WOŁOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1001', '10', '1001', 'BEŁCHATOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1007', '10', '1007', 'OPOCZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1436', '14', '1436', 'ZWOLEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1062', '10', '1062', 'M. PIOTRKÓW TRYBUNALSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3018', '30', '3018', 'OSTRZESZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('211', '2', '0211', 'LUBIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('216', '2', '0216', 'POLKOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1016', '10', '1016', 'TOMASZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1014', '10', '1014', 'SIERADZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1019', '10', '1019', 'ZDUŃSKOWOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1407', '14', '1407', 'KOZIENICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('619', '6', '0619', 'WŁODAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3017', '30', '3017', 'OSTROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('616', '6', '0616', 'RYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1401', '14', '1401', 'BIAŁOBRZESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('810', '8', '0810', 'ŻAGAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('204', '2', '0204', 'GÓROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('811', '8', '0811', 'ŻARSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3012', '30', '3012', 'KROTOSZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3061', '30', '3061', 'M. KALISZ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1006', '10', '1006', 'ŁÓDZKI WSCHODNI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1061', '10', '1061', 'M. ŁÓDŹ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('804', '8', '0804', 'NOWOSOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1020', '10', '1020', 'ZGIERSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3013', '30', '3013', 'LESZCZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3063', '30', '3063', 'M. LESZNO');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1406', '14', '1406', 'GRÓJECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3004', '30', '3004', 'GOSTYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2815', '28', '2815', 'OSTRÓDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3020', '30', '3020', 'PLESZEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2470', '24', '2470', 'M. MYSŁOWICE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2472', '24', '2472', 'M. RUDA ŚLĄSKA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1806', '18', '1806', 'KOLBUSZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1212', '12', '1212', 'OLKUSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2463', '24', '2463', 'M. CHORZÓW');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2475', '24', '2475', 'M. SOSNOWIEC');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2603', '26', '2603', 'KAZIMIERSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2478', '24', '2478', 'M. ZABRZE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2405', '24', '2405', 'GLIWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2466', '24', '2466', 'M. GLIWICE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2474', '24', '2474', 'M. SIEMIANOWICE ŚLĄSKIE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2476', '24', '2476', 'M. ŚWIĘTOCHŁOWICE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1808', '18', '1808', 'LEŻAJSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1811', '18', '1811', 'MIELECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2401', '24', '2401', 'BĘDZIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1610', '16', '1610', 'PRUDNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2465', '24', '2465', 'M. DĄBROWA GÓRNICZA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1603', '16', '1603', 'KĘDZIERZYŃSKO-KOZIELSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2462', '24', '2462', 'M. BYTOM');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1208', '12', '1208', 'MIECHOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1812', '18', '1812', 'NIŻAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2471', '24', '2471', 'M. PIEKARY ŚLĄSKIE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2413', '24', '2413', 'TARNOGÓRSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('208', '2', '0208', 'KŁODZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1605', '16', '1605', 'KRAPKOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1607', '16', '1607', 'NYSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2416', '24', '2416', 'ZAWIERCIAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1611', '16', '1611', 'STRZELECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('618', '6', '0618', 'TOMASZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2608', '26', '2608', 'PIŃCZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2409', '24', '2409', 'MYSZKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2612', '26', '2612', 'STASZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('417', '4', '0417', 'WĄBRZESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3215', '32', '3215', 'SZCZECINECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1608', '16', '1608', 'OLESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('264', '2', '0264', 'M. WROCŁAW');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1423', '14', '1423', 'PRZYSUSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('613', '6', '0613', 'PARCZEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3026', '30', '3026', 'ŚREMSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('224', '2', '0224', 'ZĄBKOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2606', '26', '2606', 'OPATOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2461', '24', '2461', 'M. BIELSKO-BIAŁA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2477', '24', '2477', 'M. TYCHY');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2210', '22', '2210', 'NOWODWORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3005', '30', '3005', 'GRODZISKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1462', '14', '1462', 'M. PŁOCK');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('806', '8', '0806', 'STRZELECKO-DREZDENECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3217', '32', '3217', 'WAŁECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('210', '2', '0210', 'LUBAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('225', '2', '0225', 'ZGORZELECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('662', '6', '0662', 'M. CHEŁM');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('617', '6', '0617', 'ŚWidNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('663', '6', '0663', 'M. LUBLIN');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('610', '6', '0610', 'ŁĘCZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1010', '10', '1010', 'PIOTRKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('614', '6', '0614', 'PUŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1003', '10', '1003', 'ŁASKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3022', '30', '3022', 'RAWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1008', '10', '1008', 'PABIANICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('203', '2', '0203', 'GŁOGOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3007', '30', '3007', 'KALISKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1013', '10', '1013', 'RAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2816', '28', '2816', 'PISKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1011', '10', '1011', 'PODDĘBICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('812', '8', '0812', 'WSCHOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2818', '28', '2818', 'GOŁDAPSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1801', '18', '1801', 'BIESZCZADZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1205', '12', '1205', 'GORLICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1262', '12', '1262', 'M. NOWY SĄCZ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1805', '18', '1805', 'JASIELSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1813', '18', '1813', 'PRZEMYSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2467', '24', '2467', 'M. JASTRZĘBIE-ZDRÓJ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2415', '24', '2415', 'WODZISŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2479', '24', '2479', 'M. ŻORY');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1816', '18', '1816', 'RZESZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1815', '18', '1815', 'ROPCZYCKO-SĘDZISZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1814', '18', '1814', 'PRZEWORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2408', '24', '2408', 'MIKOŁOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2468', '24', '2468', 'M. JAWORZNO');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('418', '4', '0418', 'WŁOCŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1424', '14', '1424', 'PUŁTUSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3028', '30', '3028', 'WĄGROWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('408', '4', '0408', 'LIPNOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1411', '14', '1411', 'MAKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3210', '32', '3210', 'MYŚLIBORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2014', '20', '2014', 'ZAMBROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1415', '14', '1415', 'OSTROŁĘCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('461', '4', '0461', 'M. BYDGOSZCZ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2002', '20', '2002', 'BIAŁOSTOCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1463', '14', '1463', 'M. RADOM');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('402', '4', '0402', 'BRODNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('404', '4', '0404', 'CHEŁMIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('414', '4', '0414', 'ŚWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2008', '20', '2008', 'MONIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3262', '32', '3262', 'M. SZCZECIN');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1465', '14', '1465', 'M. ST. WARSZAWA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3204', '32', '3204', 'GOLENIOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3201', '32', '3201', 'BIAŁOGARDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('607', '6', '0607', 'KRAŚNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('603', '6', '0603', 'CHEŁMSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('608', '6', '0608', 'LUBARTOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('615', '6', '0615', 'RADZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('809', '8', '0809', 'ZIELONOGÓRSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3010', '30', '3010', 'KONIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('202', '2', '0202', 'DZIERŻONIOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1217', '12', '1217', 'TATRZAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1219', '12', '1219', 'WIELICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1203', '12', '1203', 'CHRZANOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3213', '32', '3213', 'SŁAWIEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('808', '8', '0808', 'ŚWIEBODZIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('411', '4', '0411', 'RADZIEJOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3002', '30', '3002', 'CZARNKOWSKO-TRZCIANECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1403', '14', '1403', 'GARWOLIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1015', '10', '1015', 'SKIERNIEWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1063', '10', '1063', 'M. SKIERNIEWICE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3006', '30', '3006', 'JAROCIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('611', '6', '0611', 'ŁUKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('862', '8', '0862', 'M. ZIELONA GÓRA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3027', '30', '3027', 'TURECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1004', '10', '1004', 'ŁĘCZYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1438', '14', '1438', 'ŻYRARDOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1405', '14', '1405', 'GRODZISKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1418', '14', '1418', 'PIASECZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('601', '6', '0601', 'BIALSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('661', '6', '0661', 'M. BIAŁA PODLASKA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3011', '30', '3011', 'KOŚCIAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('802', '8', '0802', 'KROŚNIEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1005', '10', '1005', 'ŁOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1417', '14', '1417', 'OTWOCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3029', '30', '3029', 'WOLSZTYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1421', '14', '1421', 'PRUSZKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3009', '30', '3009', 'KOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1412', '14', '1412', 'MIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3062', '30', '3062', 'M. KONIN');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1426', '14', '1426', 'SIEDLECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1464', '14', '1464', 'M. SIEDLCE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1002', '10', '1002', 'KUTNOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1428', '14', '1428', 'SOCHACZEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3025', '30', '3025', 'ŚREDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('602', '6', '0602', 'BIŁGORAJSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1820', '18', '1820', 'TARNOBRZESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1818', '18', '1818', 'STALOWOWOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1864', '18', '1864', 'M. TARNOBRZEG');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('213', '2', '0213', 'MILICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2602', '26', '2602', 'JĘDRZEJOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1609', '16', '1609', 'OPOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1661', '16', '1661', 'M. OPOLE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2407', '24', '2407', 'LUBLINIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2609', '26', '2609', 'SANDOMIERSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('605', '6', '0605', 'JANOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('217', '2', '0217', 'STRZELIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('664', '6', '0664', 'M. ZAMOŚĆ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('221', '2', '0221', 'WAŁBRZYSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('263', '2', '0263', 'M. WAŁBRZYCH');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('620', '6', '0620', 'ZAMOJSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('207', '2', '0207', 'KAMIENNOGÓRSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2404', '24', '2404', 'CZĘSTOCHOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2464', '24', '2464', 'M. CZĘSTOCHOWA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2613', '26', '2613', 'WŁOSZCZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1021', '10', '1021', 'BRZEZIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1821', '18', '1821', 'LESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2216', '22', '2216', 'SZTUMSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2819', '28', '2819', 'WĘGORZEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3218', '32', '3218', 'ŁOBESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1211', '12', '1211', 'NOWOTARSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1817', '18', '1817', 'SANOCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1210', '12', '1210', 'NOWOSĄDECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2417', '24', '2417', 'ŻYWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1207', '12', '1207', 'LIMANOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1861', '18', '1861', 'M. KROSNO');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1215', '12', '1215', 'SUSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1802', '18', '1802', 'BRZOZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1807', '18', '1807', 'KROŚNIEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2403', '24', '2403', 'CIESZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2402', '24', '2402', 'BIELSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1209', '12', '1209', 'MYŚLENICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1862', '18', '1862', 'M. PRZEMYŚL');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1218', '12', '1218', 'WADOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1819', '18', '1819', 'STRZYŻOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1201', '12', '1201', 'BOCHEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2410', '24', '2410', 'PSZCZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1202', '12', '1202', 'BRZESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1213', '12', '1213', 'OŚWIĘCIMSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1216', '12', '1216', 'TARNOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1263', '12', '1263', 'M. TARNÓW');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2601', '26', '2601', 'BUSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1206', '12', '1206', 'KRAKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1261', '12', '1261', 'M. KRAKÓW');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1863', '18', '1863', 'M. RZESZÓW');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1803', '18', '1803', 'DĘBICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1804', '18', '1804', 'JAROSŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2412', '24', '2412', 'RYBNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2473', '24', '2473', 'M. RYBNIK');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2411', '24', '2411', 'RACIBORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1810', '18', '1810', 'ŁAŃCUCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2414', '24', '2414', 'BIERUŃSKO-LĘDZIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('218', '2', '0218', 'ŚREDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1204', '12', '1204', 'DĄBROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1602', '16', '1602', 'GŁUBCZYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1214', '12', '1214', 'PROSZOWICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1809', '18', '1809', 'LUBACZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2469', '24', '2469', 'M. KATOWICE');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2012', '20', '2012', 'SUWALSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2063', '20', '2063', 'M. SUWAŁKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2861', '28', '2861', 'M. ELBLĄG');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2009', '20', '2009', 'SEJNEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2201', '22', '2201', 'BYTOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1404', '14', '1404', 'GOSTYNIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3208', '32', '3208', 'KOŁOBRZESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3209', '32', '3209', 'KOSZALIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3261', '32', '3261', 'M. KOSZALIN');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2801', '28', '2801', 'BARTOSZYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2205', '22', '2205', 'KARTUSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2204', '22', '2204', 'GDAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2261', '22', '2261', 'M. GDAŃSK');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2802', '28', '2802', 'BRANIEWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2804', '28', '2804', 'ELBLĄSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2264', '22', '2264', 'M. SOPOT');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2212', '22', '2212', 'SŁUPSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2263', '22', '2263', 'M. SŁUPSK');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2262', '22', '2262', 'M. GDYNIA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2208', '22', '2208', 'LĘBORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2215', '22', '2215', 'WEJHEROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2211', '22', '2211', 'PUCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('0', '0', '0', 'BRAK DANYCH');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1431', '14', '1431', 'WARSZAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1432', '14', '1432', 'WARSZAWSKI ZACHODNI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1410', '14', '1410', 'ŁOSICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3023', '30', '3023', 'SŁUPECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3030', '30', '3030', 'WRZESIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3015', '30', '3015', 'NOWOTOMYSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1434', '14', '1434', 'WOŁOMIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1408', '14', '1408', 'LEGIONOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('805', '8', '0805', 'SŁUBICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3021', '30', '3021', 'POZNAŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3064', '30', '3064', 'M. POZNAŃ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1414', '14', '1414', 'NOWODWORSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1433', '14', '1433', 'WĘGROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1429', '14', '1429', 'SOKOŁOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('803', '8', '0803', 'MIĘDZYRZECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('807', '8', '0807', 'SULĘCIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2010', '20', '2010', 'SIEMIATYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1419', '14', '1419', 'PŁOCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3003', '30', '3003', 'GNIEŹNIEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1435', '14', '1435', 'WYSZKOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1420', '14', '1420', 'PŁOŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3024', '30', '3024', 'SZAMOTULSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3014', '30', '3014', 'MIĘDZYCHODZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('464', '4', '0464', 'M. WŁOCŁAWEK');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3016', '30', '3016', 'OBORNICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('409', '4', '0409', 'MOGILEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('801', '8', '0801', 'GORZOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('861', '8', '0861', 'M. GORZÓW WIELKOPOLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('407', '4', '0407', 'INOWROCŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1416', '14', '1416', 'OSTROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2003', '20', '2003', 'BIELSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2005', '20', '2005', 'HAJNOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('419', '4', '0419', 'ŻNIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1427', '14', '1427', 'SIERPECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('401', '4', '0401', 'ALEKSANDROWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1402', '14', '1402', 'CIECHANOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2013', '20', '2013', 'WYSOKOMAZOWIECKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3001', '30', '3001', 'CHODZIESKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('415', '4', '0415', 'TORUŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('463', '4', '0463', 'M. TORUŃ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1422', '14', '1422', 'PRZASNYSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('412', '4', '0412', 'RYPIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1437', '14', '1437', 'ŻUROMIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1461', '14', '1461', 'M. OSTROŁĘKA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('405', '4', '0405', 'GOLUBSKO-DOBRZYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('403', '4', '0403', 'BYDGOSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1413', '14', '1413', 'MŁAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('410', '4', '0410', 'NAKIELSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3019', '30', '3019', 'PILSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3212', '32', '3212', 'PYRZYCKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2061', '20', '2061', 'M. BIAŁYSTOK');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3202', '32', '3202', 'CHOSZCZEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('1425', '14', '1425', 'RADOMSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2007', '20', '2007', 'ŁOMŻYŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2062', '20', '2062', 'M. ŁOMŻA');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2803', '28', '2803', 'DZIAŁDOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3206', '32', '3206', 'GRYFIŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2811', '28', '2811', 'NidZICKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3031', '30', '3031', 'ZŁOTOWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3214', '32', '3214', 'STARGARDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2812', '28', '2812', 'NOWOMIEJSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2006', '20', '2006', 'KOLNEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('413', '4', '0413', 'SĘPOLEŃSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('406', '4', '0406', 'GRUDZIĄDZKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('2011', '20', '2011', 'SOKÓLSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('462', '4', '0462', 'M. GRUDZIĄDZ');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('3203', '32', '3203', 'DRAWSKI');
INSERT INTO uwm.powiat (id, fk_woj, kod_teryt, nazwa) VALUES ('265', '2', '0265', 'M. WAŁBRZYCH');
